### ISSUE TITLE
.nvmrc within package

### ISSUE THREAD

**Issue by WORMSS** [inspect-js/is-symbol#12]
Just wondering what benefit .nvmrc file is within the npm package?
I can understand you want it in your repo, but does it need to be in npm?

**Comment by ljharb** [comment]
There's no real benefit, but the size is effectively zero, so there's literally zero cost to having it included. The size of an installed package is largely irrelevant.

**Comment by WORMSS** [comment]
If it's irrelevant, why is it there in the first place?

**Comment by ljharb** [comment]
It's there because it's needed in dev - it's just not used by consumers.
